### ISSUE TITLE
Error when adding item

### ISSUE THREAD

**Issue by Jerico97** [cartman-2000/VirtualStorage#4]
Can't add item to the storage, the "Missing Space" label pops up, no errors in console or chat

**Comment by cartman-2000** [comment]
It's not a bug, it's a limit to the number of items a container can have that Nelson set into place a couple years ago. Without it, it would be possible to overflow containers by putting too many items in it. The container data structure in the game has the item count stored as a byte type value, so it would only be possible to have 255 items max.
